name = "cf-worker-ws-dev"
main = "src/index.js"
compatibility_date = "2024-01-01"
# node_compat = true
workers_dev = true
[[routes]]
pattern = "gcp.putrir.my.id"
custom_domain = true
[[routes]]
pattern = "shopee.co.id.gcp.putrir.my.id"
custom_domain = true
[[routes]]
pattern = "cf.shopee.co.id.gcp.putrir.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.kidskyzer.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "cvs-deo.shopeemobile.com.kidskyzer.filegear-sg.me"
custom_domain = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "1b6c1745-992e-4aac-8685-266c090e50ea"
# TROJAN_PASSWORD = "your-trojan-password"  # Optional: If not set, UUID will be used as password
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
